# Generated by Django 4.1.7 on 2023-06-27 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='código')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('codigo', models.CharField(choices=[('01', 'Taller de vajillas'), ('02', 'Taller de accesorios para el baño'), ('03', 'Taller de misceláneas')], default='01', max_length=2, primary_key=True, serialize=False, verbose_name='código')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='La cantidad de caracteres no puede ser mayor que 10'), django.core.validators.MinLengthValidator(limit_value=10, message='La cantidad de caracteres no puede ser menor que 10'), django.core.validators.RegexValidator(message='Solo puede contener números', regex='^[0-9]*$')], verbose_name='código')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('costo', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='costo')),
                ('cantidad_producida_en_el_mes', models.PositiveIntegerField(verbose_name='cantidad producida en el mes')),
                ('mes_proceso', models.DateField(default=main.models.Articulo.mes_proceso_default, verbose_name='mes de proceso')),
                ('cantidad_rechazada', models.PositiveIntegerField(verbose_name='cantidad rechazada')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taller')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_producida_en_el_mes__gt', models.F('cantidad_rechazada'))), name='check_cpm__gt__cr', violation_error_message='La cantidad producida en el mes no puede ser menor que cantidad rechazada'),
        ),
    ]
